
project_id = "naoqigivttgpkfwpzcgg"

[storage]
[storage.avatars]
public = true
[storage.rooms]
public = true
[storage.documents]
public = false

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GOOGLE_SECRET)"
