
project_id = "naoqigivttgpkfwpzcgg"

[storage]
[storage.avatars]
public = true
[storage.rooms]
public = true
[storage.documents]
public = false

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GOOGLE_SECRET)"

[functions.create-payment-order]
verify_jwt = true

[functions.firebase-auth-convert]
verify_jwt = false

[functions.verify-payment]
verify_jwt = true

[functions.razorpay-webhook]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.notify-notice-created]
verify_jwt = false

[functions.notify-document-uploaded]
verify_jwt = false

[functions.notify-chat-message]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
